import { ComparisonFeature } from "@/components/shared/ComparisonTable";

// Données de comparaison
export const features: ComparisonFeature[] = [
  // General
  {
    category: 'General',
    feature: 'Human Experience Rating',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: '1,000+ personalized AI ChatGPT messages + Calendar invitation',
    boostMyDeal: true,
    competitors: {
      Instantly: true,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'Office services to send faxes',
    boostMyDeal: 'done',
    competitors: {
      Instantly: 'basic',
      Vapi: 'API services only',
      Ava: 'done',
      Lemlist: 'Email',
      Clay: 'SMS services for number phone',
      Reoon: 'done',
      'Smartlead.ai': 'basic',
      'Apollo.ai': 'done',
      Saleshandy: 'done',
      'Close.com': 'done',
    },
  },
  {
    feature: 'Pay-per-AI/Message/Credit system',
    boostMyDeal: 'done',
    competitors: {
      Instantly: 'done',
      Vapi: false,
      Ava: 'Pay monthly',
      Lemlist: 'Pay monthly + Send number',
      Clay: 'Pay monthly',
      Reoon: 'Pay monthly',
      'Smartlead.ai': 'done',
      'Apollo.ai': 'Pay monthly',
      Saleshandy: 'Pay monthly',
      'Close.com': 'done',
    },
  },

  // SMS & Voice Features
  {
    category: 'SMS & Voice Features',
    feature: 'Pay-per-AI/Message/Credit system',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: true,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'Retell AI orchestrated system',
    boostMyDeal: true,
    competitors: {
      Instantly: true,
      Vapi: true,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': true,
      'Apollo.ai': true,
      Saleshandy: true,
      'Close.com': true,
    },
  },
  {
    feature: 'Pay-per-AI/Message/Credit system',
    boostMyDeal: true,
    competitors: {
      Instantly: true,
      Vapi: true,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': true,
      Saleshandy: true,
      'Close.com': true,
    },
  },
  {
    feature: 'Objective Handling + Advanced NLU Capabilities',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: true,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'SMS Automation',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: true,
      Reoon: true,
      'Smartlead.ai': true,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': true,
    },
  },

  // Additional features
  {
    category: 'Integration & Automation',
    feature: 'Broad messaging',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: true,
      Clay: true,
      Reoon: true,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: true,
      'Close.com': false,
    },
  },
  {
    feature: 'Multi-channel sequencing (Call + Email + SMS)',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': true,
      Saleshandy: true,
      'Close.com': true,
    },
  },
  {
    feature: 'Data security / reasoning-levels',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: true,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'WhatsApp / Instagram / Verification',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'CRM built-in',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': true,
      Saleshandy: false,
      'Close.com': true,
    },
  },
  {
    feature: 'Auto booking meetings',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: true,
      Ava: true,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'AI lead scoring',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,

      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'Multiple language available',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: true,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'Lead-enraging phone numbers',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': 'US/Canada only',
      Saleshandy: 'US/Canada only',
      'Close.com': 'US/Canada only',
    },
  },
  {
    feature: 'WhatsApp integration available',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'Get set up via spreadsheet',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: true,
      Ava: false,
      Lemlist: false,
      Clay: false,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
  {
    feature: 'No folders fees',
    boostMyDeal: true,
    competitors: {
      Instantly: false,
      Vapi: false,
      Ava: false,
      Lemlist: true,
      Clay: true,
      Reoon: false,
      'Smartlead.ai': false,
      'Apollo.ai': false,
      Saleshandy: false,
      'Close.com': false,
    },
  },
];
